#!/usr/bin/env python

import os

files_to_avoid = (
    os.path.basename(__file__),
    '.gitignore',
    '.git',
)

for filename in os.listdir(os.path.dirname(__file__)):
    source = os.path.join(os.path.abspath(os.path.dirname(__file__)), filename)
    dest = os.path.join('~', filename)
    os.symlink(src, dest)
    print(f'Linking {source} => {dest')
